name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install maui
        run: dotnet workload install maui
        
      - name: Install code signing
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATE_MAC }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
      
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_MAC }}
          P12_PASSWORD: ${{ secrets.CERTIFICATES_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MAC_PUBLISH_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
              CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
              PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
              KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

              # import certificate and provisioning profile from secrets
              echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
              echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

              # create temporary keychain
              security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
              security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
              security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

              # import certificate to keychain
              security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
              security list-keychain -d user -s $KEYCHAIN_PATH

              # apply provisioning profile
              mkdir -p ~/Library/MobileDevice/Provisioning Profiles\ Profiles
              cp $PP_PATH ~/Library/MobileDevice/Provisioning Profiles\ Profiles
      
      - name: Restore packages
        run: dotnet restore

      - name: Build mac app
        run: dotnet build 'ServiceBusManager/ServiceBusManager.csproj' --no-restore -c Release -f net7.0-maccatalyst /p:ApplicationVersion=${GITHUB_RUN_ID} -o '/package' 
      
      - name: Upload app to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: /package/AzServiceBus-1.0.pkg
          app-type: osx
          issuer-id: ${{ secrets.APPSTORE_API_ISSUER }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_KEY }}
          
          
