name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install maui
        run: dotnet workload install maui
        
      - name: Install code signing
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATE_MAC }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
      
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MAC_PUBLISH_PROFILE }}

        run: |
              # create variables
              PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

              # apply provisioning profile
              mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
              cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      # - name: Download Apple Provisioning Profiles
      #   uses: Apple-Actions/download-provisioning-profiles@v1
      #   with:
      #     bundle-id: 'hindrikes.se.azservicebus'
      #     issuer-id: ${{ secrets.APPSTORE_API_ISSUER }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_KEY }}
      
      - name: Restore packages
        run: dotnet restore

      - name: Build mac app
        run: dotnet build 'ServiceBusManager/ServiceBusManager.csproj' --no-restore -c Release -f net7.0-maccatalyst /p:ApplicationVersion=${{ env.RUN_ID }} -o '/package' 
      
      - name: Upload app to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: /package/AzServiceBus-1.0.pkg
          app-type: osx
          issuer-id: ${{ secrets.APPSTORE_API_ISSUER }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_KEY }}
          
          
